### PR TITLE
Feature/kalecgos health sync between realms

### PR DESCRIPTION
**Pull request by buza-me**
The feature is untested, the DBM version is unchanged. A big part of the logic is borrowed from my Sunwell WA pack for TBC, but there may be mistakes because it is a DBM adaptation. Normally DBM scans the health of the target/focus/boss1/boss2 etc. units to see if the bosses are registered and if yes updates the DBM health bars. On Kalecgos encounter, bosses are in two different rooms and are unreachable, so one player can't scan the hp of the bosses in both realms. That is why there has to be used addon message API or SendSync DBM API to inform the players in the different realms.

On combat start there will be a single round of sync messages with the names of the raiders that have the DBM version with this PR. They are saved in the boss mod state as health sync senders. Then periodically the code iterates over the sorted names of the senders. If the player is the first raider in the list with one of the bosses targeted, then it sends a sync message. Otherwise it does nothing. This is done for anti spam purposes.

### CODE REVIEW

**Comment by broizter** [comment]
That's a great feature. I will most likely do Sunwell tomorrow so I will share this version to a few people to try it out before merging.

**Comment by buza-me** [comment]
I've tested and fixed some minor issues on the Stormforge Netherwing TBC server that has support for 3.3.5 client. The latest update seems to work fine.

**Comment by broizter** [comment]
This change causes a lua error and many of the timers not to function when pulling the boss.

```lua
1x DBM-Sunwell\Kalecgos.lua:59: attempt to index upvalue 'berserkTimer' (a nil value)
DBM-Sunwell\KalecgosHealth.lua:147: in function `OnCombatStart'
DBM-Core-11.3.3\DBM-Core.lua:4929: in function `StartCombat'
DBM-Core-11.3.3\DBM-Core.lua:4495: in function `handler'
DBM-Core-11.3.3\DBM-Core.lua:811: in function <DBM-Core\DBM-Core.lua:790>

Locals:
self = <table> {
 SaveFramePosition = <function> @ DBM-Sunwell\KalecgosFrame.lua:165:
 InitializeMenu = <function> @ DBM-Sunwell\KalecgosFrame.lua:4:
 SyncThreshold = 8
 numBoss = 1
 ignoreBestkill = false
 modId = "DBM-Sunwell"
 UpdateColors = <function> @ DBM-Sunwell\KalecgosFrame.lua:186:
 CreateFrame = <function> @ DBM-Sunwell\KalecgosFrame.lua:148:
 UNIT_DIED = <function> @ DBM-Sunwell\Kalecgos.lua:143:
 revision = 20220518110528
 DestroyFrame = <function> @ DBM-Sunwell\KalecgosFrame.lua:172:
 creatureId = 24850
 iconRestore = <table> {}
 OnCombatStart = <function> @ DBM-Sunwell\KalecgosHealth.lua:146:
 OnSync = <function> @ DBM-Sunwell\KalecgosHealth.lua:177:
 RemoveEntry = <function> @ DBM-Sunwell\KalecgosFrame.lua:235:
 localization = <table> {}
 announces = <table> {}
 ChangeFrameOrientation = <function> @ DBM-Sunwell\KalecgosFrame.lua:176:
 optionCategories = <table> {}
 SPELL_AURA_APPLIED_DOSE = <function> @ DBM-Sunwell\Kalecgos.lua:78:
 SPELL_CAST_START = <function> @ DBM-Sunwell\Kalecgos.lua:129:
 specwarns = <table> {}
 OnCombatEnd = <function> @ DBM-Sunwell\KalecgosHealth.lua:168:
 inCombatOnlyEventsRegistered = 1
 lastWipeTime = 668259.296
 lastAntiSpam1 = 668245.065
 AddEntry = <function> @ DBM-Sunwell\KalecgosFrame.lua:220:
 inCombat = true
 groupSpells = <table> {}
 stats = <table> {}
 RAID_ROSTER_UPDATE = <function> @ DBM-Sunwell\KalecgosHealth.lua:173:
 INSTANCE_ENCOUNTER_ENGAGE_UNIT = <function> @ DBM-Sunwell\Kalecgos.lua:164:
 zones = <table> {}
 combatInfo = <table> {}
 Options = <table> {}
 buttons = <table> {}
 addon = <table> {}
 customState = <table> {}
 timers = <table> {}
 categorySort = <table> {}
 optionFuncs = <table> {}
 groupOptions = <table> {}
 SPELL_CAST_SUCCESS = <function> @ DBM-Sunwell\Kalecgos.lua:136:
 SPELL_AURA_APPLIED = <function> @ DBM-Sunwell\Kalecgos.lua:78:
 id = "Kal"
 DefaultOptions = <table> {}
 vb = <table> {}
 inCombatOnlyEvents = <table> {}
}
onCombatStart = <function> @ DBM-Sunwell\Kalecgos.lua:56:
BossHealth = <table> {
 Clear = <function> @ DBM-Core\DBM-BossHealth.lua:285:
 RemoveBoss = <function> @ DBM-Core\DBM-BossHealth.lua:336:
 RenameBoss = <function> @ DBM-Core\DBM-BossHealth.lua:401:
 IsShown = <function> @ DBM-Core\DBM-BossHealth.lua:307:
 Show = <function> defined =[C]:-1
 Update = <function> @ DBM-Core\DBM-BossHealth.lua:419:
 AddBoss = <function> defined =[C]:-1
 UpdateSettings = <function> defined =[C]:-1
 SetHeaderText = <function> @ DBM-Core\DBM-BossHealth.lua:280:
 HasBoss = <function> @ DBM-Core\DBM-BossHealth.lua:389:
 RemoveLowest = <function> @ DBM-Core\DBM-BossHealth.lua:358:
 Hide = <function> @ DBM-Core\DBM-BossHealth.lua:297:
}
getDragonHealth = <function> @ DBM-Sunwell\KalecgosHealth.lua:44:
L = <table> {
 FrameGUIMoveMe = "Move me"
 FrameClose = "Close"
 Mana = "Cost Reduce 50%"
 FrameHide = "Hide Frame"
 Haste = "Spell Haste + 100%"
 Heal = "Healing + 100%"
 Crit = "Crit Damage + 100%"
 FrameLock = "Frame Lock"
 Demon = "Sathrovarr the Corruptor"
 name = "Kalecgos"
 Hit = "Melee Hit - 50%"
 FrameTitle = "Spectral Realm"
 FrameOrientation = "Expand upwards"
 FrameClassColor = "Use Class Colors"
 Aggro = "AGGRO + 100%"
}
getDemonHealth = <function> @ DBM-Sunwell\KalecgosHealth.lua:48:
updateRoster = <function> @ DBM-Sunwell\KalecgosHealth.lua:74:
pushHealthUpdateSenderSync = <function> defined @Inter
  ---
  ```

**Comment by buza-me** [comment]
I see, very weird. Apparently it errors because the decorated OnCombatStart is using local variables in the main file. Well, that means I need to move the logic from the separate file into the main file. Will do it on Sunday.

**Comment by buza-me** [comment]
Done. I've moved the code from KalecgosHealth.lua to Kalecgos.lua and re-tested it on the Stormforge Netherwing server. Unfortunately I can't test it on Whitemane. Weird how 3.3.5 clients suddenly have different behaviors. Must be some Lua server modifications in the Whitemane client.

**Comment by broizter** [comment]
Great! I will go test it out later today, or possibly tomorrow.

**Comment by broizter** [comment]
Tested and working. Thank you very much for the contribution!

**Comment by broizter** [comment]
> Were you able to use the GM commands on the PTR?

Forgot to answer this. No, but a GM gave me some buffs and abilities so that I can kinda solo bosses. I really wish I would have access to GM commands on the PTR because that would be much easier.

**Pull request merged**
